qt_add_executable(client
    WIN32
    main.cpp
    mainwindow.h
    mainwindow.cpp
    deviceclient.h
    deviceclient.cpp
    devicemodel.h
    devicemodel.cpp
    chartpanel.h
    chartpanel.cpp
    sampledatabase.h
    sampledatabase.cpp
)

target_link_libraries(client
    PRIVATE
    common
    Qt::Core
    Qt::Gui
    Qt::Widgets
    Qt::Network
    Qt::Charts
    Qt::Sql
)
