qt_add_executable(simulator
    WIN32
    main.cpp
    device.h
    device.cpp
    deviceserver.h
    deviceserver.cpp
    gatewayuplink.h
    gatewayuplink.cpp
    simulatorwindow.h
    simulatorwindow.cpp
)

target_link_libraries(simulator
    PRIVATE
    common
    Qt::Core
    Qt::Gui
    Qt::Widgets
    Qt::Network
)
