#include "protocol.h"
#include "sample.h"

#include <QByteArray>
#include <QTextStream>

#include <limits>

namespace {

void writeCase(QTextStream& out, const char* name, const QByteArray& frame)
{
    out << name << ' ' << frame.toHex().toUpper() << '\n';
}

QByteArray sampleFrame(int deviceId, qint64 timestampMs, double temperature, double pressure,
                       double vibration)
{
    Sample sample;
    sample.deviceId    = deviceId;
    sample.timestampMs = timestampMs;
    sample.temperature = temperature;
    sample.pressure    = pressure;
    sample.vibration   = vibration;
    return Protocol::buildFrame(Protocol::MessageType::Sample, Protocol::encodeSample(sample));
}

} // namespace

int main()
{
    QTextStream out(stdout);
    out << "# Generated by DeviceLink tools/golden_dump via Protocol::buildFrame\n";
    out << "# Format: <name> <frame bytes in uppercase hex>\n";

    writeCase(out, "heartbeat",
              Protocol::buildFrame(Protocol::MessageType::Heartbeat, QByteArray()));
    writeCase(out, "sample_basic", sampleFrame(7, 1755500000123LL, 25.31, 101.28, 0.512));
    writeCase(out, "sample_signs", sampleFrame(-1, 0, -20.0, 0.0, -0.0));
    writeCase(out, "sample_extremes",
              sampleFrame(std::numeric_limits<qint32>::max(),
                          std::numeric_limits<qint64>::max(),
                          std::numeric_limits<double>::quiet_NaN(),
                          std::numeric_limits<double>::infinity(),
                          std::numeric_limits<double>::denorm_min()));
    return 0;
}